### ISSUE TITLE
add support for --token-file

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/k3s-boshrelease#27]
To be able to access the k3s cluster remotly, the bosh release should map the --token-file k3s server arg.

**Comment by obeyler** [comment]
https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kube-apiserver/templates/config/tokens.csv.erb

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-token-file
