### ISSUE TITLE
Should respect k8s node label 63 char limitation

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/k3s-boshrelease#64]
https://datatracker.ietf.org/doc/html/rfc1123
"Label key (w/o prefix) and value must be 63 characters or less" https://www.datree.io/resources/a-kubernetes-guide-for-labels-and-selectors

**Comment by metron2** [comment]
On azure, after startup:

> $ k3s kubectl get nodes
> No resources found

looked in :/var/vcap/sys/log/k3s-server/k3s-server.stderr.log
> E0301 20:18:13.343835    6354 kubelet_node_status.go:93] "Unable to register node with API server" err="Node \"k3s-server-0\" is invalid: metadata.labels: Invalid value: \"a20f483c-bd1e-41bc-b921-e042a1311a03.k3s-server.default.old-k3s.bosh\": must be no more than 63 characters" node="k3s-server-0"

In our deployment, the problem is in k3s-server/ctl
`    --node-label bosh.io/address=a20f483c-bd1e-41bc-b921-e042a1311a03.k3s-server.default.old-k3s.bosh  \`

Health check wasn't helpful here:
$ sudo monit summary | grep k3s
Process 'k3s-server'                running

**Comment by metron2** [comment]
I shared my fix, I just changed this to use the IP address instead since these labels didn't seem that useful. I can retarget to this repo if you prefer

https://github.com/poblin-orange/k3s-boshrelease/pull/1

**Comment by poblin-orange** [comment]
@metron2 ok thks for the trace. Its ok to target poblin-orange repo (this repo only used for final publication and issues).

**Comment by poblin-orange** [comment]
I think the issue is only for  bosh.io/address label. Seems the azure cpi (or your azure bosh configuration) sets the bosh-dns name in spec.address.
On vsphere and openstack cpi, spec.address gives the ip.

```
master/440a6ffd-5381-4d62-9afa-37d4323ad39e:~# kubectl describe node worker-0
Name:               worker-0
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    bosh.io/address=192.168.65.44
                    bosh.io/az=r2-z2
                    bosh.io/bootstrap=true
                    bosh.io/index=0
                    bosh.io/name=worker
                    k3s.io/external-ip=10.118.43.88
                    k3s.io/hostname=worker-0
                    k3s.io/internal-ip=192.168.65.44
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=worker-0
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=k3s
                    svccontroller.k3s.cattle.io/enablelb=true
                    topology.kubernetes.io/zone=r2-z2
...
```

We can target the fix only on bosh.io/address, using spec.ip instead of spec.address to be portable for all iaas

**Comment by poblin-orange** [comment]
Related bosh configuration using dns alias in spec.address: https://bosh.io/docs/dns/#job-address
